baseURL = "https://tylermadonna.com"
title = "Tyler Madonna"
theme = "coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Tyler Madonna"
description = "Talking Tech With Tyler"
keywords = "blog,developer,personal,android,ios"
info = ["Software Engineer"]
#avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
since = 2022
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customSCSS = ["scss/style.scss"]

[taxonomies]
category = "categories"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/tjmadonna"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-envelope"
weight = 2
url = "mailto:tyler@tylermadonna.com"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/tylermadonna"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 3
url = "contact/"